version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: conserjeria
      MYSQL_USER: conserjeria
      MYSQL_PASSWORD: 79z#5RX&qq5z
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  conserjeria_app:
    build: .
    container_name: conserjeria_app_mariadb
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      DB_USERNAME: conserjeria
      DB_PASSWORD: 79z#5RX&qq5z
      DB_PLATFORM: mysql
      DB_DDL_MODE: dropCreate
      DB_NAME: conserjeria
      DB_URL: jdbc:mysql://mariadb:3306/conserjeria?useSSL=false&serverTimezone=UTC
      APP_PORT: 8080
    restart: unless-stopped

volumes:
  mariadb_data:
